EXTENDED_CAP = {
    0: "20_40_BSS_Coexistence_Management_Support",
    1: "Reserved_1",
    2: "Extended_Channel_Switching",
    3: "Reserved_2",
    4: "PSMP_Capability",
    5: "Reserved_3",
    6: "SPSMP_Support",
    7: "Event",
    8: "Diagnostics",
    9: "Multicast_Diagnostic",
    10: "Location_Tracking",
    11: "FMS",
    12: "Proxy_Arp_Service",
    13: "Collocated_Interference_Reporting",
    14: "Civic_Location",
    15: "Geospatial_Location",
    16: "TFS",
    17: "WNM_Sleep_Mode",
    18: "TIM_Broadcast",
    19: "BSS_Transition",
    20: "QoS_Traffic_Capability",
    21: "AC_Station_Count",
    22: "Multiple_BSSID",
    23: "Timing_Measurement",
    24: "Channel_Usage",
    25: "SSID_List",
    26: "DMS",
    27: "UTC_Timing",
    28: "TPU_Buffer_STA_Support",
    29: "TDLS_Peer_PSM",
    30: "TDLS_Channel_Switching",
    31: "Interworking",
    32: "QoS_Map",
    33: "EBR",
    34: "SSPN_Interface",
    35: "Reserved_4",
    36: "MSGCF_Capability",
    37: "TDLS_Support",
    38: "TDLS_Prohibited",
    39: "TDLS_Channel_Switching_Prohibited",
    40: "Reject_Unadmitted_Frame",
    41: "Service_Interval_Granularity",
    42: "Service_Interval_Granularity",
    43: "Service_Interval_Granularity",
    44: "Identifier_Location",
    45: "U_APSD_Coexistence",
    46: "WNM_Notification",
    47: "QAB_Capability",
    48: "UTF_8_SSID",
    49: "QMF_Activated",
    50: "QMF_ReconfigurationActivated",
    51: "Robust_AV_Streaming",
    52: "Advanced_GCR",
    53: "Mesh_GCR",
    54: "SCS",
    55: "QLoad_Report",
    56: "Alternate_EDCA",
    57: "Unprotected_TXOP",
    58: "Protected_RXOP",
    59: "Reserved_5",
    60: "Protected_QLoad_Report",
    61: "TDLS_Wide_Bandwidth",
    62: "Operating_Mode_Notification",
    63: "Max_Number_Of_MSDUs_In_A_MPDU",
    64: "Max_Number_Of_MSDUs_In_A_MPDU",
    65: "Channel_Schedule_Management",
    66: "Geodatabase_Inband_Enabling_Signal",
    67: "Network_Channel_Control",
    68: "White_Space_Map",
    69: "Channel_Availability_Query",
    70: "FTM_Responder",
    71: "FTM_Initiator",
    72: "Reserved_6",
    73: "ESM_Capability",
    74: "Future_Channel_Guidance",
}

HT_CAP = [
    "L_SIG_TXOP_Protection",
    "Forty_Mhz_Intolerant",
    "PSMP",
    "DSSS_CCK",
    "Max_A_MSDU",
    "Delayed_BlockAck",
    "Rx_STBC",
    "Tx_STBC",
    "Short_GI_40Mhz",
    "Short_GI_20Mhz",
    "Green_Field",
    "SM_Power_Save",
    "Supported_Channel_Width",
    "LDPC_Coding_Capability",
    "res1",
    "Min_MPDCU_Start_Spacing",
    "Max_A_MPDU_Length_Exponent",
    "res2",
    "TX_Unequal_Modulation",
    "TX_Max_Spatial_Streams",
    "TX_RX_MCS_Set_Not_Equal",
    "TX_MCS_Set_Defined",
    "res3",
    "RX_Highest_Supported_Data_Rate",
    "res4",
    "RX_MSC_Bitmask",
    "res5",
    "RD_Responder",
    "HTC_HT_Support",
    "MCS_Feedback",
    "res6",
    "PCO_Transition_Time",
    "PCO",
    "res7",
    "Channel_Estimation_Capability",
    "CSI_max_n_Rows_Beamformer_Supported",
    "Compressed_Steering_n_Beamformer_Antennas_Supported",
    "Noncompressed_Steering_n_Beamformer_Antennas_Supported",
    "CSI_n_Beamformer_Antennas_Supported",
    "Minimal_Grouping",
    "Explicit_Compressed_Beamforming_Feedback",
    "Explicit_Noncompressed_Beamforming_Feedback",
    "Explicit_Transmit_Beamforming_CSI_Feedback",
    "Explicit_Compressed_Steering",
    "Explicit_Noncompressed_Steering",
    "Explicit_CSI_Transmit_Beamforming",
    "Calibration",
    "Implicit_Trasmit_Beamforming",
    "Transmit_NDP",
    "Receive_NDP",
    "Transmit_Staggered_Sounding",
    "Receive_Staggered_Sounding",
    "Implicit_Transmit_Beamforming_Receiving",
]
