HEADER = [
    "Timestamp",
    "MAC Address",
    "Channel",
    "DS Channel",
    "SN",
    "Vendor Specific Tags",
    "SSID",
    "VHT Capabilities",
    "HE Capabilities",
    "Length",
    "Label",
    "Supported Rates 1",
    "Supported Rates 2",
    "Supported Rates 3",
    "Supported Rates 4",
    "Supported Rates 5",
    "Supported Rates 6",
    "Supported Rates 7",
    "Supported Rates 8",
    "Extended Supported Rates 1",
    "Extended Supported Rates 2",
    "Extended Supported Rates 3",
    "Extended Supported Rates 4",
    "Extended Supported Rates 5",
    "Extended Supported Rates 6",
    "Extended Supported Rates 7",
    "Extended Supported Rates 8",
    "L_SIG_TXOP_Protection",
    "Forty_Mhz_Intolerant",
    "PSMP",
    "DSSS_CCK",
    "Max_A_MSDU",
    "Delayed_BlockAck",
    "Rx_STBC",
    "Tx_STBC",
    "Short_GI_40Mhz",
    "Short_GI_20Mhz",
    "Green_Field",
    "SM_Power_Save",
    "Supported_Channel_Width",
    "LDPC_Coding_Capability",
    "res1",
    "Min_MPDCU_Start_Spacing",
    "Max_A_MPDU_Length_Exponent",
    "res2",
    "TX_Unequal_Modulation",
    "TX_Max_Spatial_Streams",
    "TX_RX_MCS_Set_Not_Equal",
    "TX_MCS_Set_Defined",
    "res3",
    "RX_Highest_Supported_Data_Rate",
    "res4",
    "RX_MSC_Bitmask",
    "res5",
    "RD_Responder",
    "HTC_HT_Support",
    "MCS_Feedback",
    "res6",
    "PCO_Transition_Time",
    "PCO",
    "res7",
    "Channel_Estimation_Capability",
    "CSI_max_n_Rows_Beamformer_Supported",
    "Compressed_Steering_n_Beamformer_Antennas_Supported",
    "Noncompressed_Steering_n_Beamformer_Antennas_Supported",
    "CSI_n_Beamformer_Antennas_Supported",
    "Minimal_Grouping",
    "Explicit_Compressed_Beamforming_Feedback",
    "Explicit_Noncompressed_Beamforming_Feedback",
    "Explicit_Transmit_Beamforming_CSI_Feedback",
    "Explicit_Compressed_Steering",
    "Explicit_Noncompressed_Steering",
    "Explicit_CSI_Transmit_Beamforming",
    "Calibration",
    "Implicit_Trasmit_Beamforming",
    "Transmit_NDP",
    "Receive_NDP",
    "Transmit_Staggered_Sounding",
    "Receive_Staggered_Sounding",
    "Implicit_Transmit_Beamforming_Receiving",
    "20_40_BSS_Coexistence_Management_Support",
    "Reserved_1",
    "Extended_Channel_Switching",
    "Reserved_2",
    "PSMP_Capability",
    "Reserved_3",
    "SPSMP_Support",
    "Event",
    "Diagnostics",
    "Multicast_Diagnostic",
    "Location_Tracking",
    "FMS",
    "Proxy_Arp_Service",
    "Collocated_Interference_Reporting",
    "Civic_Location",
    "Geospatial_Location",
    "TFS",
    "WNM_Sleep_Mode",
    "TIM_Broadcast",
    "BSS_Transition",
    "QoS_Traffic_Capability",
    "AC_Station_Count",
    "Multiple_BSSID",
    "Timing_Measurement",
    "Channel_Usage",
    "SSID_List",
    "DMS",
    "UTC_Timing",
    "TPU_Buffer_STA_Support",
    "TDLS_Peer_PSM",
    "TDLS_Channel_Switching",
    "Interworking",
    "QoS_Map",
    "EBR",
    "SSPN_Interface",
    "Reserved_4",
    "MSGCF_Capability",
    "TDLS_Support",
    "TDLS_Prohibited",
    "TDLS_Channel_Switching_Prohibited",
    "Reject_Unadmitted_Frame",
    "Service_Interval_Granularity",
    "Identifier_Location",
    "U_APSD_Coexistence",
    "WNM_Notification",
    "QAB_Capability",
    "UTF_8_SSID",
    "QMF_Activated",
    "QMF_ReconfigurationActivated",
    "Robust_AV_Streaming",
    "Advanced_GCR",
    "Mesh_GCR",
    "SCS",
    "QLoad_Report",
    "Alternate_EDCA",
    "Unprotected_TXOP",
    "Protected_RXOP",
    "Reserved_5",
    "Protected_QLoad_Report",
    "TDLS_Wide_Bandwidth",
    "Operating_Mode_Notification",
    "Max_Number_Of_MSDUs_In_A_MPDU",
    "Channel_Schedule_Management",
    "Geodatabase_Inband_Enabling_Signal",
    "Network_Channel_Control",
    "White_Space_Map",
    "Channel_Availability_Query",
    "FTM_Responder",
    "FTM_Initiator",
    "Reserved_6",
    "ESM_Capability",
    "Future_Channel_Guidance",
]
